// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { frontmatter as fm0, toc as t0 } from '/Users/shilei/code/x-render/docs/form-demo/advanced-slimrender.md?type=frontmatter';
import { demoIndex as dmi0 } from '/Users/shilei/code/x-render/docs/form-demo/advanced-slimrender.md?type=demo-index';
import { frontmatter as fm1, toc as t1 } from '/Users/shilei/code/x-render/docs/form-demo/test/disaply-column.md?type=frontmatter';
import { demoIndex as dmi1 } from '/Users/shilei/code/x-render/docs/form-demo/test/disaply-column.md?type=demo-index';
import { frontmatter as fm2, toc as t2 } from '/Users/shilei/code/x-render/docs/table-render/promptly-search.md?type=frontmatter';
import { demoIndex as dmi2 } from '/Users/shilei/code/x-render/docs/table-render/promptly-search.md?type=demo-index';
import { frontmatter as fm3, toc as t3 } from '/Users/shilei/code/x-render/docs/form-demo/advanced-validate.md?type=frontmatter';
import { demoIndex as dmi3 } from '/Users/shilei/code/x-render/docs/form-demo/advanced-validate.md?type=demo-index';
import { frontmatter as fm4, toc as t4 } from '/Users/shilei/code/x-render/docs/schema-builder-online/index.md?type=frontmatter';
import { demoIndex as dmi4 } from '/Users/shilei/code/x-render/docs/schema-builder-online/index.md?type=demo-index';
import { frontmatter as fm5, toc as t5 } from '/Users/shilei/code/x-render/docs/form-demo/advanced-linkage.md?type=frontmatter';
import { demoIndex as dmi5 } from '/Users/shilei/code/x-render/docs/form-demo/advanced-linkage.md?type=demo-index';
import { frontmatter as fm6, toc as t6 } from '/Users/shilei/code/x-render/docs/form-demo/advaced-example.md?type=frontmatter';
import { demoIndex as dmi6 } from '/Users/shilei/code/x-render/docs/form-demo/advaced-example.md?type=demo-index';
import { frontmatter as fm7, toc as t7 } from '/Users/shilei/code/x-render/docs/form-demo/advanced-layout.md?type=frontmatter';
import { demoIndex as dmi7 } from '/Users/shilei/code/x-render/docs/form-demo/advanced-layout.md?type=demo-index';
import { frontmatter as fm8, toc as t8 } from '/Users/shilei/code/x-render/docs/form-demo/advanced-widget.md?type=frontmatter';
import { demoIndex as dmi8 } from '/Users/shilei/code/x-render/docs/form-demo/advanced-widget.md?type=demo-index';
import { frontmatter as fm9, toc as t9 } from '/Users/shilei/code/x-render/docs/table-render/custom-table.md?type=frontmatter';
import { demoIndex as dmi9 } from '/Users/shilei/code/x-render/docs/table-render/custom-table.md?type=demo-index';
import { frontmatter as fm10, toc as t10 } from '/Users/shilei/code/x-render/docs/form-demo/disaply-search.md?type=frontmatter';
import { demoIndex as dmi10 } from '/Users/shilei/code/x-render/docs/form-demo/disaply-search.md?type=demo-index';
import { frontmatter as fm11, toc as t11 } from '/Users/shilei/code/x-render/docs/form-demo/advanced-bind.md?type=frontmatter';
import { demoIndex as dmi11 } from '/Users/shilei/code/x-render/docs/form-demo/advanced-bind.md?type=demo-index';
import { frontmatter as fm12, toc as t12 } from '/Users/shilei/code/x-render/docs/form-demo/advanced-path.md?type=frontmatter';
import { demoIndex as dmi12 } from '/Users/shilei/code/x-render/docs/form-demo/advanced-path.md?type=demo-index';
import { frontmatter as fm13, toc as t13 } from '/Users/shilei/code/x-render/docs/table-render/collapsed.md?type=frontmatter';
import { demoIndex as dmi13 } from '/Users/shilei/code/x-render/docs/table-render/collapsed.md?type=demo-index';
import { frontmatter as fm14, toc as t14 } from '/Users/shilei/code/x-render/docs/table-render/valueType.md?type=frontmatter';
import { demoIndex as dmi14 } from '/Users/shilei/code/x-render/docs/table-render/valueType.md?type=demo-index';
import { frontmatter as fm15, toc as t15 } from '/Users/shilei/code/x-render/docs/form-demo/display-row.md?type=frontmatter';
import { demoIndex as dmi15 } from '/Users/shilei/code/x-render/docs/form-demo/display-row.md?type=demo-index';
import { frontmatter as fm16, toc as t16 } from '/Users/shilei/code/x-render/docs/table-render/noSearch.md?type=frontmatter';
import { demoIndex as dmi16 } from '/Users/shilei/code/x-render/docs/table-render/noSearch.md?type=demo-index';
import { frontmatter as fm17, toc as t17 } from '/Users/shilei/code/x-render/docs/tools/proptypes/index.md?type=frontmatter';
import { demoIndex as dmi17 } from '/Users/shilei/code/x-render/docs/tools/proptypes/index.md?type=demo-index';
import { frontmatter as fm18, toc as t18 } from '/Users/shilei/code/x-render/docs/form-demo/api-schema.md?type=frontmatter';
import { demoIndex as dmi18 } from '/Users/shilei/code/x-render/docs/form-demo/api-schema.md?type=demo-index';
import { frontmatter as fm19, toc as t19 } from '/Users/shilei/code/x-render/docs/schema-builder/index.md?type=frontmatter';
import { demoIndex as dmi19 } from '/Users/shilei/code/x-render/docs/schema-builder/index.md?type=demo-index';
import { frontmatter as fm20, toc as t20 } from '/Users/shilei/code/x-render/docs/table-render/migrate.md?type=frontmatter';
import { demoIndex as dmi20 } from '/Users/shilei/code/x-render/docs/table-render/migrate.md?type=demo-index';
import { frontmatter as fm21, toc as t21 } from '/Users/shilei/code/x-render/docs/table-render/toolbar.md?type=frontmatter';
import { demoIndex as dmi21 } from '/Users/shilei/code/x-render/docs/table-render/toolbar.md?type=demo-index';
import { frontmatter as fm22, toc as t22 } from '/Users/shilei/code/x-render/docs/form-demo/api-props.md?type=frontmatter';
import { demoIndex as dmi22 } from '/Users/shilei/code/x-render/docs/form-demo/api-props.md?type=demo-index';
import { frontmatter as fm23, toc as t23 } from '/Users/shilei/code/x-render/docs/form-demo/changelog.md?type=frontmatter';
import { demoIndex as dmi23 } from '/Users/shilei/code/x-render/docs/form-demo/changelog.md?type=demo-index';
import { frontmatter as fm24, toc as t24 } from '/Users/shilei/code/x-render/docs/form-demo/test/test.md?type=frontmatter';
import { demoIndex as dmi24 } from '/Users/shilei/code/x-render/docs/form-demo/test/test.md?type=demo-index';
import { frontmatter as fm25, toc as t25 } from '/Users/shilei/code/x-render/docs/schema-builder/api.md?type=frontmatter';
import { demoIndex as dmi25 } from '/Users/shilei/code/x-render/docs/schema-builder/api.md?type=demo-index';
import { frontmatter as fm26, toc as t26 } from '/Users/shilei/code/x-render/docs/table-render/basic.md?type=frontmatter';
import { demoIndex as dmi26 } from '/Users/shilei/code/x-render/docs/table-render/basic.md?type=demo-index';
import { frontmatter as fm27, toc as t27 } from '/Users/shilei/code/x-render/docs/table-render/index.md?type=frontmatter';
import { demoIndex as dmi27 } from '/Users/shilei/code/x-render/docs/table-render/index.md?type=demo-index';
import { frontmatter as fm28, toc as t28 } from '/Users/shilei/code/x-render/docs/tools/vscode/index.md?type=frontmatter';
import { demoIndex as dmi28 } from '/Users/shilei/code/x-render/docs/tools/vscode/index.md?type=demo-index';
import { frontmatter as fm29, toc as t29 } from '/Users/shilei/code/x-render/docs/data-render/index.md?type=frontmatter';
import { demoIndex as dmi29 } from '/Users/shilei/code/x-render/docs/data-render/index.md?type=demo-index';
import { frontmatter as fm30, toc as t30 } from '/Users/shilei/code/x-render/docs/form-demo/migrate.md?type=frontmatter';
import { demoIndex as dmi30 } from '/Users/shilei/code/x-render/docs/form-demo/migrate.md?type=demo-index';
import { frontmatter as fm31, toc as t31 } from '/Users/shilei/code/x-render/docs/table-render/tabs.md?type=frontmatter';
import { demoIndex as dmi31 } from '/Users/shilei/code/x-render/docs/table-render/tabs.md?type=demo-index';
import { frontmatter as fm32, toc as t32 } from '/Users/shilei/code/x-render/docs/playground/index.md?type=frontmatter';
import { demoIndex as dmi32 } from '/Users/shilei/code/x-render/docs/playground/index.md?type=demo-index';
import { frontmatter as fm33, toc as t33 } from '/Users/shilei/code/x-render/docs/table-render/api.md?type=frontmatter';
import { demoIndex as dmi33 } from '/Users/shilei/code/x-render/docs/table-render/api.md?type=demo-index';
import { frontmatter as fm34, toc as t34 } from '/Users/shilei/code/x-render/docs/form-demo/index.md?type=frontmatter';
import { demoIndex as dmi34 } from '/Users/shilei/code/x-render/docs/form-demo/index.md?type=demo-index';
import { frontmatter as fm35, toc as t35 } from '/Users/shilei/code/x-render/docs/form-demo/faq.md?type=frontmatter';
import { demoIndex as dmi35 } from '/Users/shilei/code/x-render/docs/form-demo/faq.md?type=demo-index';
import { frontmatter as fm36, toc as t36 } from '/Users/shilei/code/x-render/docs/index.en-US.md?type=frontmatter';
import { demoIndex as dmi36 } from '/Users/shilei/code/x-render/docs/index.en-US.md?type=demo-index';
import { frontmatter as fm37, toc as t37 } from '/Users/shilei/code/x-render/docs/index.zh-CN.md?type=frontmatter';
import { demoIndex as dmi37 } from '/Users/shilei/code/x-render/docs/index.zh-CN.md?type=demo-index';

export const filesMeta = {
  'docs/form-demo/advanced-slimrender': {
    frontmatter: fm0,
    toc: t0,
    demoIndex: dmi0,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/form-demo/advanced-slimrender.md?type=text'),
  },
  'docs/form-demo/test/disaply-column': {
    frontmatter: fm1,
    toc: t1,
    demoIndex: dmi1,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/form-demo/test/disaply-column.md?type=text'),
  },
  'docs/table-render/promptly-search': {
    frontmatter: fm2,
    toc: t2,
    demoIndex: dmi2,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/table-render/promptly-search.md?type=text'),
  },
  'docs/form-demo/advanced-validate': {
    frontmatter: fm3,
    toc: t3,
    demoIndex: dmi3,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/form-demo/advanced-validate.md?type=text'),
  },
  'docs/schema-builder-online/index': {
    frontmatter: fm4,
    toc: t4,
    demoIndex: dmi4,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/schema-builder-online/index.md?type=text'),
  },
  'docs/form-demo/advanced-linkage': {
    frontmatter: fm5,
    toc: t5,
    demoIndex: dmi5,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/form-demo/advanced-linkage.md?type=text'),
  },
  'docs/form-demo/advaced-example': {
    frontmatter: fm6,
    toc: t6,
    demoIndex: dmi6,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/form-demo/advaced-example.md?type=text'),
  },
  'docs/form-demo/advanced-layout': {
    frontmatter: fm7,
    toc: t7,
    demoIndex: dmi7,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/form-demo/advanced-layout.md?type=text'),
  },
  'docs/form-demo/advanced-widget': {
    frontmatter: fm8,
    toc: t8,
    demoIndex: dmi8,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/form-demo/advanced-widget.md?type=text'),
  },
  'docs/table-render/custom-table': {
    frontmatter: fm9,
    toc: t9,
    demoIndex: dmi9,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/table-render/custom-table.md?type=text'),
  },
  'docs/form-demo/disaply-search': {
    frontmatter: fm10,
    toc: t10,
    demoIndex: dmi10,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/form-demo/disaply-search.md?type=text'),
  },
  'docs/form-demo/advanced-bind': {
    frontmatter: fm11,
    toc: t11,
    demoIndex: dmi11,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/form-demo/advanced-bind.md?type=text'),
  },
  'docs/form-demo/advanced-path': {
    frontmatter: fm12,
    toc: t12,
    demoIndex: dmi12,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/form-demo/advanced-path.md?type=text'),
  },
  'docs/table-render/collapsed': {
    frontmatter: fm13,
    toc: t13,
    demoIndex: dmi13,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/table-render/collapsed.md?type=text'),
  },
  'docs/table-render/valueType': {
    frontmatter: fm14,
    toc: t14,
    demoIndex: dmi14,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/table-render/valueType.md?type=text'),
  },
  'docs/form-demo/display-row': {
    frontmatter: fm15,
    toc: t15,
    demoIndex: dmi15,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/form-demo/display-row.md?type=text'),
  },
  'docs/table-render/noSearch': {
    frontmatter: fm16,
    toc: t16,
    demoIndex: dmi16,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/table-render/noSearch.md?type=text'),
  },
  'docs/tools/proptypes/index': {
    frontmatter: fm17,
    toc: t17,
    demoIndex: dmi17,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/tools/proptypes/index.md?type=text'),
  },
  'docs/form-demo/api-schema': {
    frontmatter: fm18,
    toc: t18,
    demoIndex: dmi18,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/form-demo/api-schema.md?type=text'),
  },
  'docs/schema-builder/index': {
    frontmatter: fm19,
    toc: t19,
    demoIndex: dmi19,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/schema-builder/index.md?type=text'),
  },
  'docs/table-render/migrate': {
    frontmatter: fm20,
    toc: t20,
    demoIndex: dmi20,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/table-render/migrate.md?type=text'),
  },
  'docs/table-render/toolbar': {
    frontmatter: fm21,
    toc: t21,
    demoIndex: dmi21,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/table-render/toolbar.md?type=text'),
  },
  'docs/form-demo/api-props': {
    frontmatter: fm22,
    toc: t22,
    demoIndex: dmi22,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/form-demo/api-props.md?type=text'),
  },
  'docs/form-demo/changelog': {
    frontmatter: fm23,
    toc: t23,
    demoIndex: dmi23,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/form-demo/changelog.md?type=text'),
  },
  'docs/form-demo/test/test': {
    frontmatter: fm24,
    toc: t24,
    demoIndex: dmi24,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/form-demo/test/test.md?type=text'),
  },
  'docs/schema-builder/api': {
    frontmatter: fm25,
    toc: t25,
    demoIndex: dmi25,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/schema-builder/api.md?type=text'),
  },
  'docs/table-render/basic': {
    frontmatter: fm26,
    toc: t26,
    demoIndex: dmi26,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/table-render/basic.md?type=text'),
  },
  'docs/table-render/index': {
    frontmatter: fm27,
    toc: t27,
    demoIndex: dmi27,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/table-render/index.md?type=text'),
  },
  'docs/tools/vscode/index': {
    frontmatter: fm28,
    toc: t28,
    demoIndex: dmi28,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/tools/vscode/index.md?type=text'),
  },
  'docs/data-render/index': {
    frontmatter: fm29,
    toc: t29,
    demoIndex: dmi29,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/data-render/index.md?type=text'),
  },
  'docs/form-demo/migrate': {
    frontmatter: fm30,
    toc: t30,
    demoIndex: dmi30,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/form-demo/migrate.md?type=text'),
  },
  'docs/table-render/tabs': {
    frontmatter: fm31,
    toc: t31,
    demoIndex: dmi31,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/table-render/tabs.md?type=text'),
  },
  'docs/playground/index': {
    frontmatter: fm32,
    toc: t32,
    demoIndex: dmi32,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/playground/index.md?type=text'),
  },
  'docs/table-render/api': {
    frontmatter: fm33,
    toc: t33,
    demoIndex: dmi33,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/table-render/api.md?type=text'),
  },
  'docs/form-demo/index': {
    frontmatter: fm34,
    toc: t34,
    demoIndex: dmi34,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/form-demo/index.md?type=text'),
  },
  'docs/form-demo/faq': {
    frontmatter: fm35,
    toc: t35,
    demoIndex: dmi35,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/form-demo/faq.md?type=text'),
  },
  'docs/index.en-US': {
    frontmatter: fm36,
    toc: t36,
    demoIndex: dmi36,
    textGetter: () => import(/* webpackChunkName: "meta__docs" */'/Users/shilei/code/x-render/docs/index.en-US.md?type=text'),
  },
  'docs/index.zh-CN': {
    frontmatter: fm37,
    toc: t37,
    demoIndex: dmi37,
    textGetter: () => import(/* webpackChunkName: "meta__docs__zh-CN" */'/Users/shilei/code/x-render/docs/index.zh-CN.md?type=text'),
  },
}

export { tabs as tabsMeta } from './tabs';
